# Question - 3

In [2]:
import numpy as np
import pickle as pkl
import pandas as pd
import matplotlib.pyplot as plot
import random
from mpl_toolkits import mplot3d
import matplotlib.axes as axes

### Generating The Function points for the plot

In [3]:
def q3_function(parameters):
    x = parameters[0]
    y = parameters[1]
    t = x**2 + y**2
    return (50/9*(t**3) - 209/18*(t**2) + 59/9*(t))
def gradient_function(parameters):
    x = parameters[0]
    y = parameters[1]
    t = x**2 + y**2
    t_dx = x*2 
    t_dy = y*2
    f_dt = (150*(t**2) - 209*t + 59)/9
    return np.array([t_dx*f_dt, t_dy*f_dt])
def generate_points(n, t):
    '''
    We shall use this function to generate the points with random initialisation 
    as mentioned in the question. We shall take the points from the range ...
    [-10, 10]^2
    x is the 1st argument
    y is the 2nd argument
    '''
    training_set_x = []
    training_set_y = []
    for i in range(n):
        training_set_x += [[random.uniform(-t, t), random.uniform(-t, t)]]
        training_set_y += [q3_function(training_set_x[i])]
    training_set_y = np.array(training_set_y)
    training_set_x = np.array(training_set_x)
    return training_set_x, training_set_y
data_points = 500
t = 3
training_set_x, training_set_y = generate_points(data_points, t)

In [4]:
pd.DataFrame(training_set_y)

0
0       2.950378
1       1.203702
2     184.697175
3    2381.976659
4    1274.847896
..           ...
495     0.506312
496  2133.415425
497  1807.021768
498   545.555914
499   172.290676

[500 rows x 1 columns]

In [5]:
pd.DataFrame(training_set_x)

0         1
0    1.238556  0.125199
1    0.124800 -1.142465
2    1.788875 -0.857911
3    1.072102 -2.664426
4   -1.619359 -2.051906
..        ...       ...
495  0.557195  0.808380
496 -2.818959 -0.174503
497  2.539025  1.067510
498  1.473633  1.776601
499  1.723151  0.945311

[500 rows x 2 columns]

In [6]:
def plot_points(training_set_x, training_set_y):
    # fig = plot.figure()
    # ax = plot.axes(projection = '3d', )
    # ax.scatter3D([i[0] for i in training_set_x], [i[1] for i in training_set_x], training_set_y, color = 'black')
    z = []
    for i in range(len(training_set_x)):
        for j in range(len(training_set_x)):
            temp_dict = dict()
            temp_dict['x'] = training_set_x[i][0]
            temp_dict['y'] = training_set_x[j][1]
            temp_dict['function'] = q3_function(np.array([training_set_x[i][0], training_set_x[j][1]]))
            z += [temp_dict]
    return z
# temp = pd.DataFrame(plot_points(training_set_x, training_set_y))
# temp

In [7]:
# fig = plot.figure()
# ax = plot.axes(projection='3d',)
# plot.plot(0, 0, 0, 'ro')
# ax.scatter3D(list(temp['x']), list(temp['y']), list(temp['function']))
# plot.savefig('./q3.png')
# plot.show()

In [8]:
# fig = plot.figure()
# plot.plot(0, 0, 0, 'ro')
# plot.tricontourf(list(temp['x']), list(temp['y']), list(temp['function']))
# plot.savefig('./data.png')
# plot.show()

In [9]:
def contour_plot(seq_1, loss_seq_1, ground_truth):
    fig = plot.figure()
    ax = plot.axes()
    x = list(seq_1[0])
    y = list(seq_1[1])
    z = loss_seq_1
    plot.plot(ground_truth[0], ground_truth[1], 'yo')
    plot.tricontourf(list(temp['x']), list(temp['y']), list(temp['function']))
    for i in range(len(seq_1)-1):
        plot.arrow(x=x[i], y =y[i], dx = x[i+1] - x[i], dy = y[i+1] - y[i], width=0.01)
    plot.tight_layout()
    plot.show()

In [30]:
epochs = 10000
learning_rate = 0.01 # Is kind of safe learning rate
max_limit_1 = 2
# w_init = np.array([random.uniform(-1*max_limit_1, max_limit_1), random.uniform(-1*max_limit_1, max_limit_1)])
w_init = np.array([0.5, 0.4])
tolerence = 0.01

In [31]:
def gradient_descent_step(weight_now, learning_rate, tolerence):
    gradient = gradient_function(weight_now)
    print(weight_now)
    weight_new = weight_now - learning_rate*gradient
    loss = q3_function(weight_new)
    if(loss < tolerence):
        print("Loss: ", loss)
        return weight_new, loss, 0
    return weight_new, loss, 1

In [32]:
w_now = w_init
print("Initial Parameters:")
print(w_init)
seq_1 = []
loss_seq_1 = []
for i in range(epochs):
    seq_1 += [w_now]
    w_now, loss, cont = gradient_descent_step(w_now, learning_rate=learning_rate, tolerence=tolerence)
    loss_seq_1 += [loss]
    if(not cont):
        print("OK")
        print("Epochs: ", i+1)
        break
if(cont):
    print("Epochs", epochs)
print("Final Paramters")
print(w_now)

Initial Parameters:
[0.5 0.4]
[0.5 0.4]
[0.50163889 0.40131111]
[0.50354003 0.40283203]
[0.5057455 0.4045964]
[0.50830404 0.40664323]
[0.51127213 0.40901771]
[0.51471506 0.41177205]
[0.51870811 0.41496649]
[0.52333778 0.41867022]
[0.52870288 0.42296231]
[0.5349154  0.42793232]
[0.54210067 0.43368053]
[0.55039638 0.4403171 ]
[0.55994952 0.44795962]
[0.57090982 0.45672785]
[0.5834176  0.46673408]
[0.59758351 0.47806681]
[0.61345678 0.49076542]
[0.63097976 0.50478381]
[0.64993003 0.51994402]
[0.6698603  0.53588824]
[0.69006166 0.55204933]
[0.70959237 0.56767389]
[0.72741311 0.58193049]
[0.74262423 0.59409938]
[0.75471399 0.60377119]
[0.76367519 0.61094015]
[0.76991822 0.61593458]
[0.77405533 0.61924427]
[0.77669715 0.62135772]
[0.77834146 0.62267317]
[0.77934784 0.62347827]
[0.77995726 0.62396581]
[0.78032387 0.62425909]
[0.78054353 0.62443482]
[0.78067482 0.62453986]
[0.78075319 0.62460255]
[0.78079992 0.62463993]
[0.78082777 0.62466221]
[0.78084436 0.62467549]
[0.78085425 0.6246834 ]
[0

In [33]:
seq_1

[array([0.5, 0.4]),
 array([0.50163889, 0.40131111]),
 array([0.50354003, 0.40283203]),
 array([0.5057455, 0.4045964]),
 array([0.50830404, 0.40664323]),
 array([0.51127213, 0.40901771]),
 array([0.51471506, 0.41177205]),
 array([0.51870811, 0.41496649]),
 array([0.52333778, 0.41867022]),
 array([0.52870288, 0.42296231]),
 array([0.5349154 , 0.42793232]),
 array([0.54210067, 0.43368053]),
 array([0.55039638, 0.4403171 ]),
 array([0.55994952, 0.44795962]),
 array([0.57090982, 0.45672785]),
 array([0.5834176 , 0.46673408]),
 array([0.59758351, 0.47806681]),
 array([0.61345678, 0.49076542]),
 array([0.63097976, 0.50478381]),
 array([0.64993003, 0.51994402]),
 array([0.6698603 , 0.53588824]),
 array([0.69006166, 0.55204933]),
 array([0.70959237, 0.56767389]),
 array([0.72741311, 0.58193049]),
 array([0.74262423, 0.59409938]),
 array([0.75471399, 0.60377119]),
 array([0.76367519, 0.61094015]),
 array([0.76991822, 0.61593458]),
 array([0.77405533, 0.61924427]),
 array([0.77669715, 0.62135772

In [34]:
loss_seq_1

[1.1183687054014804,
 1.1177285121801876,
 1.1168669515917,
 1.1157074556699846,
 1.1141471018477982,
 1.1120477335611658,
 1.109224299066285,
 1.1054297466083955,
 1.1003358687307991,
 1.0935098100579301,
 1.0843868292238215,
 1.0722418468692858,
 1.0561661491986474,
 1.0350625272365814,
 1.0076833101377618,
 0.972751048298738,
 0.9292158690825416,
 0.8766994743960543,
 0.8161161906387369,
 0.7502985125497288,
 0.6841968089267869,
 0.6240776496023681,
 0.575547679662229,
 0.5413140372015981,
 0.5203458552522253,
 0.5091304598392323,
 0.5038013388029956,
 0.5014970627641713,
 0.5005673499976062,
 0.5002096529235365,
 0.5000762441020932,
 0.5000274545441812,
 0.5000098265800119,
 0.5000035043550728,
 0.5000012469910695,
 0.5000004431488643,
 0.5000001573606268,
 0.5000000558521283,
 0.5000000198181214,
 0.5000000070309358,
 0.5000000024941409,
 0.5000000008847154,
 0.5000000003138121,
 0.5000000001113092,
 0.5000000000394795,
 0.5000000000140039,
 0.5000000000049676,
 0.5000000000017613

In [39]:
print(gradient_function(parameters=[0.78086881, 0.62469505]))

[6.19843228e-08 4.95874584e-08]
